# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- branches/foreign+vector

pool:
  vmImage: 'Ubuntu-16.04'

steps:
# - task: JavaToolInstaller@0
#   inputs:
#     versionSpec: '11'
#     jdkArchitectureOption: x64
#     jdkSourceOption: azureStorage
#     jdkDestinationDirectory: jdk

- script: |
   sudo apt-get install libclang-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev libcups2-dev libfreetype6-dev libasound2-dev
  displayName: 'install dependencies'

- script: bash configure --with-libclang=/usr/lib/llvm-3.8/
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'branches/foreign+vector'))
  displayName: 'configure'

- script: bash configure
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'branches/foreign+vector'))
  displayName: 'configure'

- script: |
    make images docs
  displayName: 'make'
